apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-pv
  labels:
    volume-type: minecraft
spec:
  capacity:
    storage: 50Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /mnt/disk/minecraft
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-purpose
          operator: In
          values:
          - minecraft
